channels:
- bioconda
- conda-forge
dependencies:
- python=3.11.5
- numpy=1.25.2
- pandas=2.0.3
- scipy=1.11.2
- matplotlib=3.7.2
- pyyaml=6.0.1
- plotly=5.16.1
- rust=1.72.1
- dotmap=1.3.30 # only for convert_dante_config.py
