channels:
- bioconda
- conda-forge
dependencies:
- anaconda::mypy
- bioconda::pysam
- conda-forge::biopython
- conda-forge::pip
- dotmap=1.3.30  # only for convert_dante_config.py
- matplotlib=3.8.3
- numpy=1.26.4
- pandas=2.2.1
- plotly=5.16.1
- pyarrow=15.0.0  # future requirement for pandas
- pytest=8.1.1  # for testing only
- python=3.12.2
- pyyaml=6.0.1
- rust=1.74
- samtools=1.18
- scipy=1.12.0
