channels:
- anaconda
- bioconda
- conda-forge
dependencies:
- conda-forge::biopython
- dotmap=1.3.30
- anaconda::jinja2
- matplotlib=3.8.3
- anaconda::mypy
- numpy=1.26.4
- pandas=2.2.1
- conda-forge::pip
- plotly=5.16.1
- pyarrow=15.0.0
- pylint
- bioconda::pysam
- pytest=8.1.1
- python=3.12.2
- pyyaml=6.0.1
- rust=1.74
- samtools=1.18
- scipy=1.12.0
- anaconda::spyder
- conda-forge::vulture
