channels:
- anaconda
- bioconda
- conda-forge
dependencies:
- anaconda::jinja2
- anaconda::mypy
- anaconda::spyder
- bioconda::pysam
- conda-forge::biopython
- conda-forge::pip
- conda-forge::pyinstaller
- conda-forge::vulture
- dotmap=1.3.30
- matplotlib=3.8.3
- numpy=1.26.4
- pandas=2.2.1
- plotly=5.16.1
- pyarrow=15.0.0
- pylint
- pytest=8.1.1
- python=3.12.2
- pyyaml=6.0.1
- rust=1.90
- samtools=1.21
- scipy=1.12.0
