channels:
- bioconda
- conda-forge
dependencies:
- dotmap=1.3.30 # only for convert_dante_config.py
- matplotlib=3.7.2
- numpy=1.25.2
- pandas=2.2.0
- plotly=5.16.1
- pyarrow=15.0.0 # future requirement for pandas
- python=3.11.5
- pyyaml=6.0.1
- rust=1.72.1
- samtools=1.18
- scipy=1.11.2
